language: java
jdk: openjdk13
addons:
  sonarcloud:
    organization: team-chip-tuning
    token:
      secure: c8YE9BTb6ycVDUhk1d2ak7IVdf8ENoeuIVYzTuDPNCex1mNL1r2V3pVPp6oxDMeEVtH7bVdiviEdrTLLJB3yZrTYn6fBUxat7M1CQZk7BK2pZSgMLWLPIOd3MnerpGOZWd+L+6jfSsntUig73ujClmdtf0PQh7GE1xxRt88ahbqeiqSeSZYj3HRq7pHZWdMNVbGVZhnVY28DC3NLl5xHVlDPGd1qwuBPs2O7W1uItq8Xsp4FmGEYxAcVKQomArNg3jm+v+LBhfoSlkEAOT7dnun+IfJYgRjq9SYtpHQNeifKK8ppldmkMtUJb3arjIOIjEX4PSSBkHI/u3uB0H2ty1WVawdpMVHdbne+VLQgcJJmz0ptcV0AtevnqsYyoNYZG5NumZZqaNp1CC8KvUoz3qIC8hm1TBLDVehRuy0SSK2i0nExnuwe5zGtNM5tMVauJtWpNNJ0UkGclSxh53XBds551TKD7HIuk9ui4KbtfmA5bGAOuCw88fQiZwayHOWlra0y2EJ7IwVV+TJOFG2P+PhBhm8HDPjlglLM+EUISHrJDXnr1YHx9RgRycbMqUZ4lBvFS96hf0b7gRMvZ3qZsUghcvYGSFkwKAiE8s5fa30fjv1i7XQLkbGYTpQEZT6N6P+YWbsabsjjohsPL/V5nhHmzmuctpX2PsG+eeB+OOg=
script:
  - mvn clean verify sonar:sonar
cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/.sonar/cache"
env:
  global:
    secure: c8YE9BTb6ycVDUhk1d2ak7IVdf8ENoeuIVYzTuDPNCex1mNL1r2V3pVPp6oxDMeEVtH7bVdiviEdrTLLJB3yZrTYn6fBUxat7M1CQZk7BK2pZSgMLWLPIOd3MnerpGOZWd+L+6jfSsntUig73ujClmdtf0PQh7GE1xxRt88ahbqeiqSeSZYj3HRq7pHZWdMNVbGVZhnVY28DC3NLl5xHVlDPGd1qwuBPs2O7W1uItq8Xsp4FmGEYxAcVKQomArNg3jm+v+LBhfoSlkEAOT7dnun+IfJYgRjq9SYtpHQNeifKK8ppldmkMtUJb3arjIOIjEX4PSSBkHI/u3uB0H2ty1WVawdpMVHdbne+VLQgcJJmz0ptcV0AtevnqsYyoNYZG5NumZZqaNp1CC8KvUoz3qIC8hm1TBLDVehRuy0SSK2i0nExnuwe5zGtNM5tMVauJtWpNNJ0UkGclSxh53XBds551TKD7HIuk9ui4KbtfmA5bGAOuCw88fQiZwayHOWlra0y2EJ7IwVV+TJOFG2P+PhBhm8HDPjlglLM+EUISHrJDXnr1YHx9RgRycbMqUZ4lBvFS96hf0b7gRMvZ3qZsUghcvYGSFkwKAiE8s5fa30fjv1i7XQLkbGYTpQEZT6N6P+YWbsabsjjohsPL/V5nhHmzmuctpX2PsG+eeB+OOg=
