# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    container_name: "guest-house"
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: guest-house