# default postgres image: https://hub.docker.com/_/postgres
# In PROD please use other security user
#
# @author dani
version: '3.1'

services:
  db:
    container_name: "guest-house"
    image: postgres:alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: guest-house