spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
  datasource:
    name: guest-house
    url: jdbc:h2:mem:guest-house
    data-username: postgres
    data-password: mysecretpassword